scss_files: 'scss/**/*.scss'

exclude: 'scss/external/**/*.scss'

linters:
  # border: 0 -> border: none
  BorderZero:
    convention: none

  # color: white などの利用を禁止
  ColorKeyword:
    enabled: true

  # color: $body-color のように変数を強制する
  ColorVariable:
    enabled: false

  # /* */ でのコメントを禁止
  Comment:
    enabled: false

  # @extend, @include, @content の記述順をスコープの先頭に強制する
  DeclarationOrder:
    enabled: false

  # ルール間に改行を強制する
  EmptyLineBetweenBlocks:
    enabled: true

  # 空のルールを禁止する
  EmptyRule:
    enabled: true

  # IDセレクタに対するスタイル付けを禁止する
  IdSelector:
    enabled: true

  # !importantを禁止する
  ImportantRule:
    enabled: true

  # opacity: 0.5 -> opacity: .5
  LeadingZero:
    enabled: true

  # 変数名の命名規則を定義する
  NameFormat:
    convention: '^[a-z][-a-z0-9_]*$'

  # ネストの深さを制限する (default: 3)
  NestingDepth:
    max_depth: 5

  # プロパティの記述順を強制する
  PropertySortOrder:
    enabled: false

  # div.selector などの書き方を制限する
  QualifyingElement:
    allow_element_with_attribute: true
    allow_element_with_class: true

  # セレクタの深さを制限する (default: 3)
  SelectorDepth:
    max_depth: 6

  # セレクタの名前のルールを定義する (default: hyphenated_lowercase)
  SelectorFormat:
    ignored_names:
      - 'fb_iframe_widget'  # facebook widget
      - 'field_with_errors' # generated by rails
    ignored_types:
      - 'id'

  # color: #ff0000 -> color: #f00 のように短い記述を強制する
  Shorthand:
    enabled: true

  SpaceAfterComma:
    exclude:
      - 'app/assets/stylesheets/shared/colors.scss'

  # p{} -> p {} のようにスペースを強制する
  SpaceBeforeBrace:
    allow_single_line_padding: true

  SpaceBetweenParens:
    exclude:
      - 'app/assets/stylesheets/shared/colors.scss'

  # 文字列を表すクォートの種類を指定する (default: single_quotes)
  StringQuotes:
    style: single_quotes

  # 必要のないvendor-prefixの記述を禁止する
  VendorPrefix:
    enabled: false