baseurl = 'http://www.othlo.tech'
#baseurl = 'https://othlotech.github.io/OthloTech/'
title = 'OthloTech -学生クリエイティブ集団-'
languageCode = 'ja'

# Google Analytics
googleAnalytics = 'UA-78315006-1'
# ページネーション
paginate = 10
# 日本語対策
hasCJKLanguage = true

[params]
  viewMorePostLink = '/blog/'
  author = 'OthloTech'
  email = 'othlotech@gmail.com'
  about_us = '<p>OthloTechは、東海圏のエンジニア・デザイナーを中心とするクリエイティブな学生が集まるコミュニティです。</p>'
  copyright = '© 2016 OthloTech. All rights reserved. Crafted with love'
  date_format = '2016-01-02'
  logo = '/images/logo.png'
  twitter = 'OthloTech'
  facebook = 'othlotech'
  github = 'OthloTech'

[Permalinks]
  blog = '/blog/:year/:month/:day/:filename/'

[[params.menu]]
  name = 'HOME'
  url = '/'
  weight = 1

[[params.menu]]
  name = 'EVENTS'
  url = '/events/'
  weight = 2

#[[params.menu]]
#  name = 'BLOG'
#  url = '/posts/'
#  weight = 3

[[params.menu]]
  name = 'MEMBER'
  url = '/member/'
  weight = 4

[[params.menu]]
  name = 'ABOUT'
  url = '/about/'
  weight = 5

[[params.menu]]
  name = 'CONTACT'
  url = '/contact/'
  weight = 6

[params.widgets]
  categories = true
  tags = true
  search = true

[params.carousel]
  enable = true
  # /data/carousel に格納

[params.features]
  enable = true
  # /data/features に格納

[params.members]
  enable = true
  # /data/members に格納
  title = 'メンバー'
  subtitle = ''

[params.see_more]
  enable = true
  icon = 'fa fa-calendar'
  title = 'OthloEvent'
  subtitle = 'OthloTechは月に一度のペースで勉強会やLT会などのイベントを開催しています。'
  link_url = '/events/'
  link_text = '過去のイベントを見る'

[params.clients]
  enable = true
  # /data/clients に格納
  title = 'プロダクト'
  subtitle = ''

[params.recent_posts]
  enable = false
  title = 'OthloTechの活動ブログ'
  subtitle = '日常的なことや技術的なことを週に一度のペースで書いていきます∩(ﾟ∀ﾟ∩)'

email = 'othlotech@gmail.com'
name = 'OthloTech'
description = 'OthloTechは、東海圏のエンジニア・デザイナーを中心とするクリエイティブな学生が集まるコミュニティです。'
homepage = 'http://www.othlo.tech'
tags = ['OthloTech', '学生', 'クリエイティブ', '名古屋', '勉強会']
features = ['OthloTech', '学生', 'クリエイティブ', '名古屋', '勉強会']
min_version = 0.1
