version: 1
runtime: go
api_version: go1
 
handlers:

- url: /
  static_files: dist/views/top/main.html
  upload: dist/views/top/main.html

- url: /about
  static_files: dist/views/top/about.html
  upload: dist/views/top/about.html

- url: /css/(.*)
  static_files: dist/css/\1
  upload: dist/css/(.*)

- url: /js/(.*)
  static_files: dist/js/\1
  upload: dist/js/(.*)

- url: /images/(.*)
  static_files: dist/images/\1
  upload: dist/images/(.*)

- url: /fonts/(.*)
  static_files: dist/fonts/\1
  upload: dist/fonts/(.*)

- url: /events/(.*)
  static_files: dist/views/events/\1
  upload: dist/events/(.*)



- url: /.*
  script: _go_app


# When certain errors occur, App Engine serves a generic error page. You can configure your app 
# to serve a custom static file instead of these generic error pages.
error_handlers:
  - file: dist/views/errors/default_error.html
  # Google App Engine quota exceeded.
  - error_code: over_quota
    file: dist/views/errors/over_quota.html
  # Served to any client blocked by your app's DoS Protection configuration.
  - error_code: dos_api_denial
    file: dist/views/errors/dos_api_denial.html
  # Served if a deadline is reached before there is a response from your app.
  - error_code: timeout
    file: dist/views/errors/timeout.html

threadsafe: true
automatic_scaling:
  min_idle_instances: automatic   # idle状態にあるインスタンスの最小値
  max_idle_instances: 1                 # idle状態にあるインスタンスの最大値
  min_pending_latency: 3000ms  # リクエストを処理するまでに許される待ち時間の最小
  max_pending_latency: automatic
