version: 1
runtime: go
api_version: go1
 
handlers:
- url: images/
  static_dir: ../dist/images

- url: css/
  static_dir: ../dist/css

- url: js/
  static_dir: ../dist/js

- url: fonts/
  static_dir: ../dist/fonts

- url: views/
  static_dir: ../dist/views/

- url: /.*
  script: _go_app

threadsafe: true
automatic_scaling:
  min_idle_instances: automatic   # idle状態にあるインスタンスの最小値
  max_idle_instances: 1                 # idle状態にあるインスタンスの最大値
  min_pending_latency: 3000ms  # リクエストを処理するまでに許される待ち時間の最小
  max_pending_latency: automatic